<<<<<<< HEAD
git@github.com:alejandro-mancebo/assignment.git

=======
>>>>>>> ffca836ce6d49cd3accc1f91b2c1ed106439d8f0
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
